# Generated by Django 6.0.4 on 2026-04-17 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_number', models.IntegerField()),
                ('iban', models.CharField()),
                ('currency', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('name_other_party', models.CharField()),
                ('iban_other_party', models.CharField()),
                ('authorization_code', models.CharField()),
                ('description', models.TextField()),
                ('is_not_fixed', models.BooleanField()),
                ('code', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
